### ISSUE TITLE
quat = 0 0 0 0 is not allowed

### ISSUE THREAD

**Issue by zhan72** [gemcollector/maniwhere#2]
<img width="406" alt="微信图片_20241119173812" src="https://github.com/user-attachments/assets/8faa7db4-44e4-4a22-b7e6-1b6b6c2c1658">

**Comment by gemcollector** [comment]
what is your mujoco version? And which task do you use to run the env?

**Comment by zhan72** [comment]
Thanks for your reply!
I use mujoco 3.2.5 to run the "train.sh"

**Comment by gemcollector** [comment]
I suggest you to mujoco `2.3.7`, which aligns with our conda yaml.

**Comment by zhan72** [comment]
Thanks!
