### ISSUE TITLE
How long you trained the robot in the virtual environment？

### ISSUE THREAD

**Issue by zlm200** [gemcollector/maniwhere#6]
I conducted experiments with the UR5's lift task and did not make any modifications to the parameters or network except for changing the batch size. After training for 800,500 frames across 1601 episodes, the highest reward I achieved during testing was 171.407994780545. Throughout the entire training process, the robot did not complete a single lift task successfully. Could you tell me how long you trained the robot in the virtual environment before it was able to learn this skill?I have attached the training log file and eval log file for your reference.
[eval.csv](https://github.com/user-attachments/files/17933499/eval.csv)
[train.csv](https://github.com/user-attachments/files/17933502/train.csv)

**Comment by gemcollector** [comment]
Hi, there. Sorry for the late due to the exam. Have you adjusted some params? I ran the bash files this afternoon. I upload my 
[eval.csv](https://github.com/user-attachments/files/17961365/eval.csv). You can check this file. And have you install the conda envs aligned with the `yaml` file? Otherwise, it might be the broken seed or instability from RL.

**Comment by zlm200** [comment]
Thank you for your response. However, I still have some confusion about episode_reward. I reviewed your eval.csv file, but the episode_reward does not seem to meet the success threshold (which is 250 for success). The highest episode_reward in the eval.csv file is 171.407994780545. Can the policy  be directly transferred to a real robot?

**Comment by gemcollector** [comment]
sorry for the mistake lol. 
I directly uploaded exactly your eval.csv.  orz. 

Here is my result: 
[eval.csv](https://github.com/user-attachments/files/17963862/eval.csv).
And I also uploaded my previous training logs for your reference. 
https://drive.google.com/drive/folders/1uXguPzVeNE76BGpjiAGd20qnd5CVrCiu?usp=drive_link

**Comment by zlm200** [comment]
Thank you so much for your response. After checking, I found that the issue was with the `dmc` library in my environment. When I ran the code for the first time, I encountered the error "ImportError: Cannot initialize a headless EGL display." I mistakenly commented out the line `os.environ['MUJOCO_GL'] = 'egl'` in the code. On my second attempt, I resolved the issue by using the command `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libffi.so.7`, and after running the code without modifying the original script, I was able to get results similar to yours. This has been very encouraging for my work, and I plan to deploy it on the Sawyer robot for real-world experimental trials moving forward.

**Comment by xavhl** [comment]
> sorry for the mistake lol. I directly uploaded exactly your eval.csv. orz.
> 
> Here is my result: [eval.csv](https://github.com/user-attachments/files/17963862/eval.csv). And I also uploaded my previous training logs for your reference. https://drive.google.com/drive/folders/1uXguPzVeNE76BGpjiAGd20qnd5CVrCiu?usp=drive_link

Hi thanks for your work! I have 2 questions:

1. Reproduction

I tried to reproduce `ur5_lift` task as in [scripts/train.sh](https://github.com/gemcollector/maniwhere/blob/master/scripts/train.sh). My eval script output: `seed 1, success rate: 0.58`. Was there something wrong in my trial? If I understood correctly, the result presented in paper was 0.8X in Table 1.

2. Params for other envs

Did other envs use the same set of parameters (e.g. num frames, aux lr) as `ur5_lift` in [scripts/train.sh](https://github.com/gemcollector/maniwhere/blob/master/scripts/train.sh)? Could you kindly share if not?

Thank you!

**Comment by gemcollector** [comment]
> > sorry for the mistake lol. I directly uploaded exactly your eval.csv. orz.
> > Here is my result: [eval.csv](https://github.com/user-attachments/files/17963862/eval.csv). And I also uploaded my previous training logs for your reference. https://drive.google.com/drive/folders/1uXguPzVeNE76BGpjiAGd20qnd5CVrCiu?usp=drive_link
> 
> Hi thanks for your work! I have 2 questions:
> 
> 1. Reproduction
> 
> I tried to reproduce `ur5_lift` task as in [scripts/train.sh](https://github.com/gemcollector/maniwhere/blob/master/scripts/train.sh). My eval script output: `seed 1, success rate: 0.58`. Was there something wrong in my trial? If I understood correctly, the result presented in paper was 0.8X in Table 1.
> 
> 2. Params for other envs
> 
> Did other envs use the same set of parameters (e.g. num frames, aux lr) as `ur5_lift` in [scripts/train.sh](https://github.com/gemcollector/maniwhere/blob/master/scripts/train.sh)? Could you kindly share if not?
> 
> Thank you!

Thanks for your feedback. Could you first check the version of MuJoCo and dm-control?

**Comment by gemcollector** [comment]
> > sorry for the mistake lol. I directly uploaded exactly your eval.csv. orz.
> > Here is my result: [eval.csv](https://github.com/user-attachments/files/17963862/eval.csv). And I also uploaded my previous training logs for your reference. https://drive.google.com/drive/folders/1uXguPzVeNE76BGpjiAGd20qnd5CVrCiu?usp=drive_link
> 
> Hi thanks for your work! I have 2 questions:
> 
> 1. Reproduction
> 
> I tried to reproduce `ur5_lift` task as in [scripts/train.sh](https://github.com/gemcollector/maniwhere/blob/master/scripts/train.sh). My eval script output: `seed 1, success rate: 0.58`. Was there something wrong in my trial? If I understood correctly, the result presented in paper was 0.8X in Table 1.
> 
> 2. Params for other envs
> 
> Did other envs use the same set of parameters (e.g. num frames, aux lr) as `ur5_lift` in [scripts/train.sh](https://github.com/gemcollector/maniwhere/blob/master/scripts/train.sh)? Could you kindly share if not?
> 
> Thank you!

I sincerely apologize — I believe you had raised a question earlier, but since it was posted under a previous issue, I couldn’t locate it at the time and assumed you had already resolved it.

Let me also address your earlier question regarding the dataset:

- If you need random data, you can directly use the images from the `moving-view`.

- If you need expert data, you could either train a few expert models yourself, or I can provide you with a checkpoint.

Once again, I’m truly sorry for having overlooked your question earlier.

**Comment by xavhl** [comment]
> Thanks for your feedback. Could you first check the version of MuJoCo and dm-control?

Hi thank you for your prompt reply! My pip package versions are as follows. I installed them according to [environment.yml](https://github.com/gemcollector/maniwhere/blob/master/environment.yml). 

```bash
(maniwhere) pip list | grep mujoco
mujoco                  2.3.7
(maniwhere) pip list | grep dm    
dm-control              1.0.14
dm-env                  1.6
dm-tree                 0.1.8
```

Or could it be due to the system MuJoCo package version? I have a different version installed from other project before.
```bash
(maniwhere) ls ~/.mujoco
mujoco210  
mujoco210-linux-x86_64.tar.gz
```

**Comment by xavhl** [comment]
> I sincerely apologize — I believe you had raised a question earlier, but since it was posted under a previous issue, I couldn’t locate it at the time and assumed you had already resolved it.
> 
> Let me also address your earlier question regarding the dataset:
> 
> * If you need random data, you can directly use the images from the `moving-view`.
> * If you need expert data, you could either train a few expert models yourself, or I can provide you with a checkpoint.
> 
> Once again, I’m truly sorry for having overlooked your question earlier.

Thanks so much for the helpful information!

By the way, for this question below,
> Did other envs use the same set of parameters (e.g. num frames, aux lr) as ur5_lift in [scripts/train.sh](https://github.com/gemcollector/maniwhere/blob/master/scripts/train.sh)? Could you kindly share if not?

For different tasks, do we just change the `task_name` and that will be enough?

**Comment by gemcollector** [comment]
> > Thanks for your feedback. Could you first check the version of MuJoCo and dm-control?
> 
> Hi thank you for your prompt reply! My pip package versions are as follows. I installed them according to [environment.yml](https://github.com/gemcollector/maniwhere/blob/master/environment.yml).
> 
> (maniwhere) pip list | grep mujoco
> mujoco                  2.3.7
> (maniwhere) pip list | grep dm    
> dm-control              1.0.14
> dm-env                  1.6
> dm-tree                 0.1.8
> Or could it be due to the system MuJoCo package version? I have a different version installed from other project before.
> 
> (maniwhere) ls ~/.mujoco
> mujoco210  
> mujoco210-linux-x86_64.tar.gz

Hi,
Here are the configs I used in my previous runs: https://drive.google.com/file/d/11YCLriAA3wSfnecz0BewG8-ZEcCNJ9qH/view?usp=sharing.  You might have hit a broken seed; could you try a few different random seeds?

**Comment by gemcollector** [comment]
> > I sincerely apologize — I believe you had raised a question earlier, but since it was posted under a previous issue, I couldn’t locate it at the time and assumed you had already resolved it.
> > Let me also address your earlier question regarding the dataset:
> > 
> > * If you need random data, you can directly use the images from the `moving-view`.
> > * If you need expert data, you could either train a few expert models yourself, or I can provide you with a checkpoint.
> > 
> > Once again, I’m truly sorry for having overlooked your question earlier.
> 
> Thanks so much for the helpful information!
> 
> By the way, for this question below,
> 
> > Did other envs use the same set of parameters (e.g. num frames, aux lr) as ur5_lift in [scripts/train.sh](https://github.com/gemcollector/maniwhere/blob/master/scripts/train.sh)? Could you kindly share if not?
> 
> For different tasks, do we just change the `task_name` and that will be enough?

https://drive.google.com/file/d/183KTERoHCwzya1g3XkZe4ikODsbUfeLj/view?usp=sharing
I have uploaded each task’s evaluation log files and the corresponding config yamls; you can check the parameters against these files.
